### ISSUE TITLE
EasyRSS/Readrops issues / greader “FAIL 64-bit or GMP extension!”

### ISSUE THREAD

**Issue by biosaat** [YunoHost-Apps/freshrss_ynh#101]
I use a fresh installation of FreshRss (Version 1.16.2~ynh1) on Yunohost 3.8.4.8. 
And EasyRss 0.7.6, Readrops 1.1.4, respectively, on Android 9 (LineageOs). 

myurl/rss/api/greader.php claims “OK”. 
myurl/rss/api/: the Google Reader API configuration test reported “FAIL 64-bit or GMP extension!”

After installing gmp (sudo apt install php-gmp), the Google Reader API configuration test PASSES.
And EasyRss starts to work properly. (Before, I could log in but no articles were loaded).

Readrops still reports “HTTP 400”.

**Comment by Alkarex** [comment]
For Readrops, the address must be something like https://freshrss.example.net/ while for EasyRSS is is something like https://freshrss.example.net/api/greader.php

**Comment by biosaat** [comment]
> For Readrops, the address must be something like https://freshrss.example.net/ while for EasyRSS it is something like https://freshrss.example.net/api/greader.php
Thanks, I was not aware of that. Now Readrops is working properly, too (having php-gmp installed - not sure how it would be without php-gmp).

**Comment by Alkarex** [comment]
`php-gmp` is needed for the API to work on 32-bit platforms.
The list of PHP packages can be seen e.g. on
https://github.com/FreshRSS/FreshRSS/blob/e9fd37e5ca8a7758343184d688d6318ff9eff8de/Docker/Dockerfile#L11-L12

**Comment by Alkarex** [comment]
See also https://github.com/FreshRSS/FreshRSS/pull/3061

**Comment by plopoyop** [comment]
It's weird since gmp belongs ton installed packages list : 
https://github.com/YunoHost-Apps/freshrss_ynh/blob/master/scripts/_common.sh#L10
