### ISSUE TITLE
Pas d'image pour le contenu Facebook dans Firefox / No image for facebook content in Firefox

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/freshrss_ynh#102]
Firefox 78.0.2
FreshRSS 1.16.2. 
YunoHost 3.8.4.9 (stable)
Extensions Firefox: toutes désactivées pour les tests

**Issue**
**Les images ne s'affichent pas dans _Firefox_**. Mais elles s'affichent dans _Safari_, _Brave_ et depuis _Reeder iOS/Mac_.

**Console Firefox**
```
Content Security Policy: Ce site possède une politique Report-Only sans URI de rapport. CSP ne bloquera pas cette politique et ne pourra pas rapporter ses violations.
Content Security Policy: « x-frame-options » ignoré en raison de la directive « frame-ancestors ».
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
```

**Logs FreshRSS**
```
in_player_instance does not exist in configuration
in_show_content does not exist in configuration
in_player_height does not exist in configuration
in_player_width does not exist in configuration
```

**Comment by plopoyop** [comment]
Je n'ai pas le même problème.
Quel flux te fais ça ? il y a des change que Firefox applique ula politique CSP mise en place par le site d'origine.

**Comment by mrtpcet** [comment]
Je viens de vérifier, et il semble en effet qu'il s'agisse essentiellement des flux rss en provenance de Facebook par RSSBridge (hébergé lui aussi sur mon yunohost)

**Comment by mrtpcet** [comment]
OK, j'ai enfin trouvé le problème : c'est l'extension **Facebook Container** qui bloquait le chargement du contenu à distance. **J'ai ajouté mon instance FreshRSS dans les sites autorisés et tout fonctionne !**
Désolé pour la fausse alerte !

---
_English_
OK, I finally found the problem: it's the **Facebook Container** extension that was blocking the remote loading of content. 
**I added my FreshRSS instance in the authorized sites and everything works !**
Sorry for the false issue!

**Comment by plopoyop** [comment]
Cool :+1:
