### ISSUE TITLE
Yunohost 4  FreshRSS install failed requirements

### ISSUE THREAD

**Issue by R-0ne** [YunoHost-Apps/freshrss_ynh#105]
hello, I can't install the app.

server Debian 10.5
YunoHost 4.0.7 (stable) 

I leave you the log here: https://paste.yunohost.org/raw/nalurokoju

**Comment by Alkarex** [comment]
The relevant error is that `pdo-mysql` seems to be missing

**Comment by R-0ne** [comment]
yes that's what I thought I understood from the log, but I don't really like doing it by hand.

So I prefer reported, is the installation of a dependency missing?

This is due to the upgrade of yunohost to version 4 and the switch to debian 10.5?

**Comment by R-0ne** [comment]
There is also this part that I do not understand, it may be from there?

Creating config file /etc/php/7.3/mods-available/pdo_sqlite.ini with new version

Creating config file /etc/php/7.3/mods-available/sqlite3.ini with new version

W: Target Translations (main/i18n/Translation-fr) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Translations (main/i18n/Translation-fr) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/extra_php_version.list:1 and /etc/apt/sources.list.d/sury.list:1

**Comment by mrtpcet** [comment]
I have the same issue !

**Comment by TheNomad11** [comment]
It might be related to this issue with TTRSS https://forum.yunohost.org/t/ttrss-ne-se-met-plus-a-jour-le-service-ne-redemarre-pas/12668/20

**Comment by ericgaspar** [comment]
Should be fixed in testing with 220e16d 

The *testing* version needs to be tested before merging to *master*... feedback will be appreciated 
`sudo yunohost app upgrade freshrss -u https://github.com/YunoHost-Apps/freshrss_ynh/tree/testing`

**Comment by yalh76** [comment]
solved now, php-mysql included

https://github.com/YunoHost-Apps/freshrss_ynh/blob/722ade2ac45b6380f30cb0817817d528f89459df/scripts/_common.sh#L9
