### ISSUE TITLE
1.16.2~ynh1 to 1.17.0~ynh1 -- mysqldump: Couldn't execute 'show create table `freshrss_rsstest_entrytmp`'

### ISSUE THREAD

**Issue by manuc66** [YunoHost-Apps/freshrss_ynh#108]
Hi,

When trying to update from `1.16.2~ynh1` to `1.17.0~ynh1` it failed

Here is the upgrade log : https://paste.yunohost.org/raw/avuwozopux

**Comment by manuc66** [comment]
After deleting the user `rsstest` the upgrade succeeded

**Comment by lapineige** [comment]
Good to know that your problem is solved :)
