### ISSUE TITLE
[SECURITY] FreshRSS database password readable by all users

### ISSUE THREAD

**Issue by Jules-Bertholet** [YunoHost-Apps/freshrss_ynh#115]
`$final_path/data/config.php`, which contains the password for the FreshRSS MySQL database, is readable by all users.

**Comment by lapineige** [comment]
I suppose we should change the access rights for this directory ?

**Comment by plopoyop** [comment]
> I suppose we should change the access rights for this file ?

Or maybe the full data directory
not sure about the best solution

**Comment by lapineige** [comment]
I don't know either :sweat_smile:

**Comment by Jules-Bertholet** [comment]
Ideally we should follow the principle of least access, so the whole folder should be resticted. But php-fpm might need to be given access with `setfacl`? Possibly `nginx` as well? I am not sure, I would need to test

**Comment by plopoyop** [comment]
I'll try on a test instance
