### ISSUE TITLE
easyrss not working (api / bad request)

### ISSUE THREAD

**Issue by f0x2501** [YunoHost-Apps/freshrss_ynh#12]
Hi, 
try to configure yunohost freshrss with api for easyrss integration.
- api is right enable
- when I try to put api password in profil section, I have a message feedback about profil update. But password still show empty value.
- I can acess https:/<domain>/rss/api/ and show "Google Reader compatible API" links. All links return "PASS"
- When I access  https:/<domain>/rss/api/greader.php it return **Bad Request!**

Of course if I try to configure easyrss from f-droid with 

```
url: https:/<domain>/rss/api/greader.php
name: my yunohost name
password: api password 
```

it doesn't work.

I read 2 post on yunohost forum, but it doesn't resolve my issue.
Hope you can help me :)

Thank you.

**Comment by plopoyop** [comment]
Hi,
I'm sorry, I did check everything and I have the same result as you but it's working for me.

What is the error message you have with easyrss ? 
Is your server a x86 or a x86_64 ? (I remember there is an issue with de x86 but I think I updated the package to be sure the right extension is installed).

**Comment by mentat-fr** [comment]
Thanks for reply,

Not x86 or x86_64, my system is Raspberry pi : 

    /sbin/init: ELF 32-bit LSB executable, ARM

So does the issue affect ARM architecture too ?

**Comment by mentat-fr** [comment]
The easyrss message

    Connexion fail, check your login or password

**Comment by plopoyop** [comment]
Can you check php5-gmp package is installed but it should be necessary only if you have the message 

> FAIL 64-bit or GMP extension

 while checking api compatibility.

can you test `grep apiPasswordHash /var/www/freshrss/data/users/clement/config.php` to be sure there is a password hash set.

**Comment by mentat-fr** [comment]
php5-gmp is installed and apiPasswordHash is set in my config.php.

**Comment by mentat-fr** [comment]
Maybe a clue, my RPi is on local network with a domain name.

Here the log

        2016-05-24T18:30:15+02:00       badRequest()
        2016-05-24T18:30:15+02:00       Array
        (
            [date] => 2016-05-24T18:30:15+02:00
            [headers] => Array
                (
                    [Host] => <mydomain>
                    [User-Agent] => Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
                    [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
                    [Accept-Language] => fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
                    [Accept-Encoding] => gzip, deflate, br
                    [Dnt] => 1
                    [Cookie] => FreshRSS=qe70nlolp69n56ql49s37c5224; SSOwAuthUser=<mylogin>; SSOwAuthHash=749e4deef1d43f41d7e30f298fd2f320; SSOwAuthExpire=1464711835.736
                    [Connection] => keep-alive
                )

            [_SERVER] => Array
                (
                    [USER] => www-data
                    [HOME] => /var/www
                    [FCGI_ROLE] => RESPONDER
                    [QUERY_STRING] =>
                    [REQUEST_METHOD] => GET
                    [CONTENT_TYPE] =>
                    [CONTENT_LENGTH] =>
                    [SCRIPT_NAME] => /rss/api/greader.php
                    [REQUEST_URI] => /rss/api/greader.php
                    [DOCUMENT_URI] => /rss/api/greader.php
                    [DOCUMENT_ROOT] => /var/www/freshrss//p/
                    [SERVER_PROTOCOL] => HTTP/1.1
                    [HTTPS] => on
                    [GATEWAY_INTERFACE] => CGI/1.1
                    [SERVER_SOFTWARE] => nginx/1.6.2
                    [REMOTE_ADDR] => 192.x.x.x
                    [REMOTE_PORT] => 44616
                    [SERVER_ADDR] => 192.x.x.x
                    [SERVER_PORT] => 443
                    [SERVER_NAME] => <mydomain>
                    [REDIRECT_STATUS] => 200
                    [REMOTE_USER] =>
                    [PATH_INFO] =>
                    [SCRIPT_FILENAME] => /var/www/freshrss//p//api/greader.php
                    [HTTP_HOST] => <mydomain>
                    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
                    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
                    [HTTP_ACCEPT_LANGUAGE] => fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
                    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
                    [HTTP_DNT] => 1
                    [HTTP_COOKIE] => FreshRSS=qe70nlolp69n56ql49s37c5224; SSOwAuthUser=<mylogin>; SSOwAuthHash=749e4deef1d43f41d7e30f298fd2f320; SSOwAuthExpire=1464711835.736

                    [HTTP_COOKIE] => FreshRSS=qe70nlolp69n56ql49s37c5224; SSOwAuthUser=<mylogin>; SSOwAuthHash=749e4deef1d43f41d7e30f298fd2f320; SSOwAuthExpire=1464711835.736
                    [HTTP_CONNECTION] => keep-alive
                    [PHP_SELF] => /rss/api/greader.php
                    [REQUEST_TIME_FLOAT] => 1464107415.7492
                    [REQUEST_TIME] => 1464107415
                )

            [_GET] => Array
                (
                )

            [_POST] => Array
                (
                )

            [_COOKIE] => Array
                (
                    [FreshRSS] => qe70nlolp69n56ql49s37c5224
                    [SSOwAuthUser] => <mylogin>
                    [SSOwAuthHash] => 749e4deef1d43f41d7e30f298fd2f320
                    [SSOwAuthExpire] => 1464711835.736
                )

            [INPUT] =>
        )

**Comment by plopoyop** [comment]
You should try to look at the logs while using easyrss application.
When you access the api through your browser it does not comply with the api therefore it's normal it does not work and the logs are irrelevant.
