### ISSUE TITLE
Can I create a user in FreshRSS without create a user in Yunohost ?

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/freshrss_ynh#121]
Hello !
I would like create a user for FreshRSS access only and without yunohost because I don't want the user have access to yunohost.
So **I can create the user** in the admin panel from FreshRSS **but the root url redirect automatically in the Yunohost's SSO** where previously created identifiers doesn't work in SSO.

Is there a way to create a user without going through yunohost ?

Thanks !

**Comment by yalh76** [comment]
Yes making the application public, and create a user as you made
