### ISSUE TITLE
Cron job file ownership not root

### ISSUE THREAD

**Issue by cheywood** [YunoHost-Apps/freshrss_ynh#126]
### Describe the bug

`/etc/cron.d/freshrss` is owned as freshrss:freshrss. With my instance this resulted in the cron job not being executed; changing ownership to root brought it back online. I didn't have the issue with previous versions.

At about the same time the server went through a YunoHost minor version update.

See other comments on #125.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.2.8
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: I don't think so
- App version 1.18-1~ynh1

```
# cat /etc/debian_version 
10.10
```

**Comment by djibux** [comment]
I can confirm that issue and the fix.

**Comment by yalh76** [comment]
solved by now

https://github.com/YunoHost-Apps/freshrss_ynh/blob/722ade2ac45b6380f30cb0817817d528f89459df/scripts/install#L132-L134
