### ISSUE TITLE
Database if not encoded in the proper UTF8 coding : how to fix it ?

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#137]
Following this issue : https://github.com/FreshRSS/FreshRSS/issues/4139

It seems by database if not using UTF8MB4 as it should be with FreshRSS, even with automatic migrations included until v1.15.

Is it safe to migrate that database ? (using this https://github.com/FreshRSS/FreshRSS/issues/4139#issuecomment-1010092428)
Will it affects other Yunohost software using MariaDB ?

Is that a Yunohost specific issue ? (can someone else check if that's happening on their side too ?)

Thank you

**Comment by lapineige** [comment]
Also, I wonder if this is related to this issue ? https://github.com/YunoHost-Apps/nextcloud_ynh/pull/384

**Comment by Alkarex** [comment]
> Also, I wonder if this is related to this issue ? [YunoHost-Apps/nextcloud_ynh#384](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/384)

Similar problem but I do not think it is related. Another Yunohost user could try a feed with emojis such as https://nitter.fdn.fr/GuillaumeRozier/rss

> Is it safe to migrate that database ? (using this [FreshRSS/FreshRSS#4139 (comment)](https://github.com/FreshRSS/FreshRSS/issues/4139#issuecomment-1010092428)) Will it affects other Yunohost software using MariaDB ?

Yes, those commands are pretty limited in scope so should be safe BUT I recommand you to use the export-to-sqlite and import-from-sqlite method instead. https://github.com/FreshRSS/FreshRSS/issues/4139#issuecomment-1010096756

**Comment by lapineige** [comment]
Well, it's easy to make a yunohost backup, then I'll just try it now 🙂

**Comment by lapineige** [comment]
That UTF encoding issue is fixed thanks to the command given (FreshRSS internal export&import database tool), so I'm closing this issue.
