### ISSUE TITLE
Problem installing the Invidious extension

### ISSUE THREAD

**Issue by blogdemoi** [YunoHost-Apps/freshrss_ynh#144]
Hi,

I wish to install the Invidious extension https://github.com/Korbak/freshrss-invidious

So I did:

```
cd /var/www/freshrss/extensions
wget https://github.com/korbak/freshrss-invidious/archive/master.zip
unzip master.zip
```

However:

`mv freshrss-invidious-master/xExtension-Invidious` doesn't work, 

> 
mv: missing destination file operand after 'freshrss-invidious-master/xExtension-Invidious'

How can I install it and a broader question, how to install other extensions?

Thank you.

**Comment by lapineige** [comment]
> mv freshrss-invidious-master/xExtension-Invidious doesn't work,

`mv` command expect 2 arguments : `sourceFileLocation FinalFileDestination` (these could be folders).

You have to specify what you're moving and where you're moving it.
