### ISSUE TITLE
actualize_script.php failed to write log : cannot create /var/log/freshrss/freshrss.log: Permission denied

### ISSUE THREAD

**Issue by xoddark** [YunoHost-Apps/freshrss_ynh#148]
### Describe the bug

After update, I receive from my Yunohost instance emails with subject :
Cron <freshrss@yunhost> /usr/bin/php7.4 /var/www/freshrss/app/actualize_script.php >/var/log/freshrss/freshrss.log 2>&1
And content :
bin/sh: 1: cannot create /var/log/freshrss/freshrss.log: Permission denied

### Context

- Hardware: *Baremetal server*
- YunoHost version: 11.0.10.2 
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Freshrss 1.20.0~ynh1
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- *Update a freshrss app to 1.20.0~ynh1*
- *Wait email send to admin*

### Expected behavior

*The actualize_script should be able to write log.*
The freshrss should be able to write log in root folder, or the folder should have good access right.

**Comment by xoddark** [comment]
If folder /var/log/freshrss_app should belong to app_user, perhaps upgrade script should ensure of that.

**Comment by pobee24** [comment]
I confirm, I get the same issue after the update.
with some help from the chat, an update of the permissions solved the problem
(sudo chown freshrss:root /var/log/freshrss)

**Comment by lapineige** [comment]
Fixed by #150

**Comment by xoddark** [comment]
@lapineige or @plopoyop : That would be good idea to release a new version with the fix, no ?

**Comment by plopoyop** [comment]
That is exactly what the fix do :
```
log_path="/var/log/$app"
mkdir -p $log_path
chown $app:www-data "$log_path"
```
The merge in master was 2 days ago, did you upgrade after this date ?

**Comment by xoddark** [comment]
The package version wasn't upgraded, so Yunohost don't propose me upgrade.
The package should not have been upgraded ?

**Comment by lapineige** [comment]
Good point, thanks !

**Comment by mateMathieu** [comment]
I still have the same message from CRON. Even if I remove and reinstall it. Do you know how to fix this?

**Comment by mateMathieu** [comment]
Bump!
The fix did not work. And I cannot reopen the issue.
