### ISSUE TITLE
RSS feeds are not updating automatically (php error in logs)

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/freshrss_ynh#149]
After update, freshrss seems not update automatically. 

I have this issue too https://github.com/YunoHost-Apps/freshrss_ynh/issues/148 and after fix permissions `sudo chown freshrss:root /var/log/freshrss`I have error in logs abd my feeds seems not updating : 

```
PHP Warning:  file_put_contents(/var/www/freshrss/data/cache/6c3884b4f64400d197db566b15407c7bd70b4f09.spc): failed to open stream: Permission denied in /var/www/freshrss/lib/SimplePie/SimplePie/Cache/File.php on line 112
PHP Warning:  /var/www/freshrss/data/cache is not writable. Make sure you've set the correct relative or absolute path, and that the location is server-writable. in /var/www/freshrss/lib/SimplePie/SimplePie.php on line 1601
```

**Context**
    Hardware: hetzner vps
    YunoHost version: 11.0.10.2
    I have access to my server: Through SSH | through the webadmin
    Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
    Using, or trying to install package version/branch: Freshrss 1.20.0~ynh1

Steps to reproduce

    Update a freshrss app to 1.20.0~ynh1
    Open log file in /var/log/freshrss

**Comment by lapineige** [comment]
#150 fixes it
