### ISSUE TITLE
Update to 1.4 - and support of wallabag v2

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#15]
Hello,
I was wondering if Wallabag v2 is supported - seems like it's the case with the next release, 1.3.2: https://github.com/FreshRSS/FreshRSS/issues/1175
(update: finally updated to 1.4, see below)

The milestone for this release is currently at 92%, I suppose a release will be published soon.
Do you need help for updating it ? I've available to do some beta-test if you need it ;)

**Comment by M5oul** [comment]
It would be great if this package could be upgraded.

**Comment by lapineige** [comment]
@plopoyop do you know if a "simple" update from FreshRSS internal would work ?
If no, how can I help you to do this update - what need to be adapted/tested /

**Comment by M5oul** [comment]
@plopoyop is not really working on it since a time now.
It would be great, If you could propose something on a `dev` branch.

**Comment by plopoyop** [comment]
There is no way in yunohost to use git branches
I usually don't update to beta, only stable.
I created a repository for the beta branch : https://github.com/plopoyop/freshrss_beta_ynh

I'm trying to get it working quickly

**Comment by lapineige** [comment]
@M5oul well I'm not super skilled in PHP - I just can do some simple tweaks - but if it's just a matter of HTML/JS/CSS I can help.
So @plopoyop, do you need any help ?
Looking at the commit list, it looks like you updated it without testing -  Is your repo already testable ?

> There is no way in yunohost to use git branches
You mean, for the updates ?

> I usually don't update to beta, only stable.
 I understand, it was only for testing purposes.

Thanks a lot for your work ;)

**Comment by plopoyop** [comment]
> There is no way in yunohost to use git branches
> You mean, for the updates ?

Yunohost only use master branch. That's why I create a new repository.

> Looking at the commit list, it looks like you updated it without testing - Is your repo already testable ?

Not on your production environnement. I usually test my release on a virtual machine. I am trying to do that today.

> Thanks a lot for your work ;)
My pleasure :)

**Comment by lapineige** [comment]
>  Yunohost only use master branch. That's why I create a new repository.
Are you sure ? Seems like they do it for wallabag https://github.com/YunoHost-Apps/wallabag_ynh/tree/testing

> Not on your production environnement. I usually test my release on a virtual machine. I am trying to do that today.
Thanks :)
I have a raspberry pi waiting for the test, I can do it if you want ;)

**Comment by M5oul** [comment]
You can clone locally, change branch `git checkout dev`.

**Comment by plopoyop** [comment]
I just created a new branch : 
https://github.com/plopoyop/freshrss_ynh/tree/freshrss-1.3.2-beta

it is working with : 
`yunohost app install https://github.com/plopoyop/freshrss_ynh/tree/freshrss-1.3.2-beta`

I tested installation, adding subcription, sharing to wallabag v2 (not working so well, into wallabag the article show with : 

> estimated reading time : < 1 min
[unable to retrieve full-text content]...

I don't really have the time to test more this week-end but, you know it won't break your testing environement if you try it.

Branching is quite great because when the final version is gonna show, mergin will be easy.
Thanks for the tip.

Have fun testing :)

**Comment by lapineige** [comment]
Thank you @plopoyop :smiley:
The 1.3.2 is out ! ;) https://github.com/FreshRSS/FreshRSS/issues/1175#issuecomment-234725787
So maybe you can update this branch to the final version, and I can test it during a few days to tell you if everything works fine ;)

I'll try your branch today :)

**Comment by plopoyop** [comment]
I'm going to update this evening.

**Comment by lapineige** [comment]
Great. Do you want me to test it right now, or should I wait for the update ?

**Comment by plopoyop** [comment]
I published reaaaaaally fast the 1.4.0 branch.
I just tested installation.
You can try it if you want.

I need to go now :)
+

**Comment by lapineige** [comment]
Hum... sadly trying to install (with yunohost app install `https://github.com/plopoyop/freshrss_ynh/tree/freshrss-1.3.2-beta` or yunohost app install `https://github.com/plopoyop/freshrss_ynh/tree/freshrss-1.4.0`) doesn't work, as it shows that FreshRSS is already installed.
I tried to change the label with -l MyLabel, it doesn't work.
Seems like I should try on another server.

**Comment by M5oul** [comment]
@plopoyop, could you work on a branch of this repository?
It's annoying to have many repositories.
You have rights on this repository.

Thanks.

**Comment by lapineige** [comment]
Oh and I'm just thinking: as FreshRSS show me an update with the internal tool, do you know what could happen if I use this tool ?
(I'm curious)
What's the difference with an update on your site ? (= what do you need to change on your side ?)
And... don't you have a way to do this kind of changes automatically ? It could avoid you to work on patching this repo.

**Comment by lapineige** [comment]
up :)

**Comment by lapineige** [comment]
ping @plopoyop :)

When trying to update, I have this warning:

 ```
$ yunohost app upgrade freshrss -u https://github.com/YunoHost-Apps/freshrss_ynh --verbose
Downloading...
Extracting...
Done.
Executing script '/var/cache/yunohost/from_file/freshrss_ynh-master/scripts/upgrade'...
+ final_path=/var/www/freshrss
+ '[' -f /var/www/freshrss/data/user.php.dist ']'
+ sudo cp update-ynh.php /var/www/freshrss/
+ sudo php /var/www/freshrss/update-ynh.php
including libs
downloading update script
Warning: PHP Notice:  Use of undefined constant FRESHRSS_UPDATE_WEBSITE - assumed 'FRESHRSS_UPDATE_WEBSITE' in /var/www/freshrss/update-ynh.php on line 10
checking if update needed
launching update
Warning: PHP Fatal error:  Call to undefined function apply_update() in /var/www/freshrss/update-ynh.php on line 23
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="refresh" content="0;url=http://nxd.securedns.dnsbycomodo.com/main?ParticipantID=gee6qoe9ve6gggov5j5qpquaqccc5fnq&FailedURI=http%3A%2F%2FFRESHRSS_UPDATE_WEBSITE%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us"/><script type="text/javascript">url="http://nxd.securedns.dnsbycomodo.com/main?ParticipantID=gee6qoe9ve6gggov5j5qpquaqccc5fnq&FailedURI=http%3A%2F%2FFRESHRSS_UPDATE_WEBSITE%2F&FailureMode=1&Implementation=&AddInType=4&Version=pywr1.0&ClientLocation=us";if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+="&w="+x+"&h="+y;}window.location.replace(url);</script></head><body></body></html>+ sudo rm /var/www/freshrss/update-ynh.php
+ sudo chown -R www-data: /var/www/freshrss/data/
+ sudo chown -R www-data: /var/www/freshrss/extensions/
+ sudo apt-get update
+ sudo apt-get install -y php5-gmp
Reading package lists...
Building dependency tree...
Reading state information...
php5-gmp is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Success! freshrss has been upgraded
Success! The SSOwat configuration has been generated
Success! Upgrade complete
```

**Comment by plopoyop** [comment]
Sorry I'm on holidays. No computer and poor Wi-Fi... 
As far as I remember, install from scratch is working but not update. i have edit the php update script to comply with new freshrss version.
I'll do that when I'll come home.

**Comment by lapineige** [comment]
> As far as I remember, install from scratch is working but not update.

Ok fine.

> i have edit the php update script to comply with new freshrss version.
I'll do that when I'll come home.

I suppose you mean you have to change it, it's not done.
Just ping me when it's done, enjoy your holidays ! ;)

(and I would be happy to look at the change, to be able to do it - in order to help you later)

**Comment by Alkarex** [comment]
Version 1.6 of FreshRSS soon ready https://github.com/FreshRSS/FreshRSS/issues/1219 :-)
By the way, let me know if things could be done to facilitate the use of FreshRSS in YunoHost

**Comment by lapineige** [comment]
Well, you made an update at the same time I created an issue ^^ #17

**Comment by plopoyop** [comment]
Ok, I'm back from holydays.
I'll try to update, we'll see how much time work will left me :)

@Alkarex, you (freshrss team) changed the update controller, so I'm reading it to understand the new logic. But if you have time to write a console based update script, it would save me lot of time. 

I don't really know how the Minz framework works. Is it possible for me to use FreshRSS_update_Controller class and to call the actions ?
Maybe we can chat later about that ?

**Comment by Alkarex** [comment]
Hello @plopoyop 
The update controller has been made by @marienfressinaud so far, and we would like to improve it https://github.com/FreshRSS/FreshRSS/issues/907
We also have a plan to provide more command line options https://github.com/FreshRSS/FreshRSS/issues/1095
I would be happy to have a chat with you (I will send you an e-mail with contact info), maybe with @marienfressinaud if he is available.

**Comment by lapineige** [comment]
Hi @plopoyop :)

For your information, I upgraded today my version using your refactoring of the update process.
However, sharing to wallabag v2 still doesn't work. The tab is opened, but wallabag don't receive the article.
Do you have this issue too ? (if you're using it)
Should I report it directly to FreshRSS team ?

**Comment by plopoyop** [comment]
I did not upgrade yet.
I just test my new upgrade system this morning but I am at work.
I need to install Wallabag V2 on my testing virtual machine.

I want to finish install refactoring, next, upgrade to 1.5 will take 5 min :)

Should be done by the end of the week.

**Comment by lapineige** [comment]
Oh ok, but it's showing version 1.4.0 in the update menu.

Anyway, there is not hurry, thanks for your work ;)

**Comment by plopoyop** [comment]
Yes, sorry, I upgrade the github repository but I didn't upgrade my own yunohost.
So, yes, if you upgrade, you have the 1.4 version installed. 

I just remember, sometime to share to wallabag, I had to do it twice. First fime I arrived to the wallabag home. Second time, it succeded. You may try that.

**Comment by lapineige** [comment]
> I just remember, sometime to share to wallabag, I had to do it twice. First fime I arrived to the wallabag home. Second time, it succeded. You may try that.
I had the same behavior in the v1.
I did in 4 times to be sure. Nothing happened.

**Comment by plopoyop** [comment]
I can't use wallabag V2 on my yunohost instance, Error 500 everywhere.
I don't know about you but, I am not sure the problem comes from FreshRss.
I'm about to finish to refactor the installation. I'll upgrade to 1.5 after.

**Comment by lapineige** [comment]
> I can't use wallabag V2 on my yunohost instance, Error 500 everywhere.

I had this previously, adding an article after login solved it.
I'll check the log after try to add an article with FreshRSS.

> I'm about to finish to refactor the installation. I'll upgrade to 1.5 after.

Great, thanks :)

**Comment by plopoyop** [comment]
> I had this previously, adding an article after login solved it.

Same problem when I manually add an article. I won't update for now

**Comment by lapineige** [comment]
I'll try again later with 1.5, and watch wallabag logs.

**Comment by plopoyop** [comment]
Outdated issue, see https://github.com/YunoHost-Apps/freshrss_ynh/issues/23
