### ISSUE TITLE
favicon don't work in 1.4

### ISSUE THREAD

**Issue by mbugeia** [YunoHost-Apps/freshrss_ynh#19]
After the upgrade the favicons are not working anymore. Checking the nginx logs it seems that the directory /var/www/freshrss/data/favicons need to be writeable by the webserver (www-data).

**Comment by plopoyop** [comment]
It's weird, after upgrade, all the data directory and all its subdirectories should belongs to www-data user :
```sudo chown -R www-data: $TMPDIR/data/ ```

can you do : 
```ls -l /var/www/freshrss/```
and 
```ls -l /var/www/freshrss/data```

**Comment by mbugeia** [comment]
I already did `sudo chown -R www-data: /var/www/freshrss/data` to fix the bug, but before that it was root:root.
To be sure I did force another upgrade and /var/www/freshrss/data was back to root:root.

**Comment by mbugeia** [comment]
Tested it with the -p option and that was correct so I fixed it ;)

**Comment by lapineige** [comment]
I had the same issue, even if sometimes the favicons were shown. I'll try to update now to test your patch ;)

**Comment by lapineige** [comment]
I confirm it's working.
Thanks :)
