### ISSUE TITLE
 sharingEnable : variable sans liaison Erreur 

### ISSUE THREAD

**Issue by siBearNetic** [YunoHost-Apps/freshrss_ynh#22]
Hello, I tried to install freshrss on my yunohost. The install failed with this message 

`Attention : ./install: ligne 97: sharingEnable : variable sans liaison
Erreur : Échec de l'installation
`

**Comment by plopoyop** [comment]
I can't test my fix cause I'am at work. But it should work.

**Comment by siBearNetic** [comment]
It works. Thank you.
