### ISSUE TITLE
Upgrading remove any extension

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#24]
Hello :)

It seems like upgrading remove all the extensions (the extension folder is removed)

Could you update the install script  to make a backup, and copy them back afterwards ? Thanks :)

edit: I found where is the issue. In this file https://github.com/YunoHost-Apps/freshrss_ynh/blob/master/scripts/upgrade  line 35
`sudo rm -rf "$FINAL_PATH"`

**Comment by lapineige** [comment]
So this remove the need to test on your side (as you mentioned here https://github.com/YunoHost-Apps/freshrss_ynh/issues/23#issuecomment-254127539).
(but you can still try my extension if you are interested ;) :D)

I'm sorry I don't have time to prepare a PR, even if it's quite trivial to fix.

**Comment by plopoyop** [comment]
Fix into https://github.com/YunoHost-Apps/freshrss_ynh/pull/30/commits/7d0beb1b7d2e04e48c3e841f0569a93393e196ee
