### ISSUE TITLE
Creating a new user in yunohost doesn"t create it correctly in FreshRSS

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#26]
Hello @plopoyop :)

I encountered a small issue when creating a new user in yunohost: it is created in FreshRSS, but weight nothing in database (0o I mean) and it looks like the tables are not created.
Deleting this user in FreshRSS and re-creating it, with same name/password, solves the problem.

Do you have an idea about what's going wrong, or do you need some logs to look into it ?
As always, I'm available for any tests that you might need ;)

Thanks for your help ! ;)

**Comment by Alkarex** [comment]
If it can help, there is now a CLI command to create a user
https://github.com/FreshRSS/FreshRSS/tree/master/cli

**Comment by plopoyop** [comment]
Hi,
I had doubt about the new package that's why I did not merge the 1.6 branch. I began to create a new branch migrating the scripts to use the CLI interface.
But, due to personal matters, I have very little time to work on the package. I'll do my best to do it the fastest I can.

**Comment by Alkarex** [comment]
@lapineige Was it related to the fact that you had set the max number of accounts to 1 in FreshRSS?

**Comment by lapineige** [comment]
> @lapineige Was it related to the fact that you had set the max number of accounts to 1 in FreshRSS?

I tested after changing the value. So I don't think it's related.

@plopoyop : I create the issue to document the problem (and a new version on other issues), not to force you to solve it as soon as possible.
So no worry, you already added the 1.6 branch, that's great ! :)
Take your time :)

Note to myself: need to find some time to send you a PR ;)

**Comment by yalh76** [comment]
There is an hook for that now https://github.com/YunoHost-Apps/freshrss_ynh/blob/master/hooks/post_user_create
