### ISSUE TITLE
Yunohost 2.5

### ISSUE THREAD

**Issue by tatapoum** [YunoHost-Apps/freshrss_ynh#28]
Bonjour,

Je viens d'installer la dernière version de Yunohost (2.5) et j'ai un souci avec FreshRSS.
L'installation de l'app se passe bien mais lorsque je clique depuis l'interface utilisateur sur le carré de FreshRSS "Fr", une courte résolution URL semble se passer avant d'être renvoyé au départ, c'est-à-dire, à l'interface utilisateur.

La log verbose de l'installation jointe.
[freshrss.txt](https://github.com/YunoHost-Apps/freshrss_ynh/files/751678/freshrss.txt)

**Comment by lapineige** [comment]
Tu as essayé avec la version 1.6 ?
De mon côté, sur une version 1.6 existante, la mise à jour vers Yunohost 2.5 s'est passée sans soucis.
Mais je n'ai pas tenté d'installation.

**Comment by tatapoum** [comment]
J'ai du repartir de la 2.5 car ma 2.4 avait quelques soucis.
Par contre, je ne vois pas comment forcer l'install de FreshRSS 1.6.
Je dois forker puis changer le numéro de version dans ma branche ?

**Comment by lapineige** [comment]
Y'a une branche 1.6 ;) https://github.com/YunoHost-Apps/freshrss_ynh/tree/freshrss-1.6
Essaye avec celle-là.

**Comment by tatapoum** [comment]
Bon, ben quand ça veut pas... :(
Même résultat avec la dernière version du script.
[freshrss_1.6.txt](https://github.com/YunoHost-Apps/freshrss_ynh/files/752332/freshrss_1.6.txt)

Du coup, je vais peut-être repartir de la 2.4...

**Comment by lyan2k** [comment]
Bonjour,
Même problème depuis l'upgrade en 2.5, je n'accède plus à freshrss. J'ai tenté upgrade, désinstallation/installation, installation de la 1.6, rien n'y fait.
Que puis-je te donner comme informations pour aider ?

**Comment by tatapoum** [comment]
Problème résolu grâce à Liberium
https://framasphere.org/posts/2824565

Il suffit de faire
`chown www-data -R /var/www/freshrss/`

**Comment by lyan2k** [comment]
ça marche du tonner! Merci!
