### ISSUE TITLE
Yunohost 2.5.4 support

### ISSUE THREAD

**Issue by Kamaluk** [YunoHost-Apps/freshrss_ynh#29]
Hey there! Will there be support for the current Yunohost built? :)

**Comment by plopoyop** [comment]
Can you give more details please.
I have 2.5.4 installed and it's working great

**Comment by Kamaluk** [comment]
Installation failed:

+ sudo service nginx reload

+ sudo rm -f /etc/nginx/conf.d/domain.ltd.d/freshrss.conf

+ sudo rm -rf /etc/cron.d/freshrss

+ sudo rm -rf /var/www/freshrss

+ mysql -u root - -e 'DROP DATABASE freshrss ; DROP USER freshrss@localhost ;'

+ domain=domain.ltd
++ sudo yunohost app setting freshrss domain

+ root_pwd=

++ sudo cat /etc/yunohost/mysql

+ db_name=freshrss

+ db_user=freshrss

Skript '/var/cache/yunohost/from_file/freshrss_ynh-master/scripts/remove' wird ausgeührt...

E: Some index files failed to download. They have been ignored, or old ones used instead.

W: Failed to fetch http://repo.yunohost.org/debian/dists/jessie/stable/binary-amd64/Packages Hash Sum mismatch

**Comment by plopoyop** [comment]
I have the same problem when I try to update yunohost.
I doesn't look like to be specific to freshrss but more a yunohost's repositories problem.

I keep the issue open for further investigation.

**Comment by lapineige** [comment]
I also saw this issue in Yunohost's forum. Maybe you will find the solution here :)

Can you install any other app ?
If you apt update/upgrade your system, is it working correctly ?

**Comment by Kamaluk** [comment]
I can install other apps, yes

**Comment by plopoyop** [comment]
Some apps don't need apt to be installed.

The probleme seems to be solved (on my server), apt-get update doesn't fail anymore.
Yunohost released a 2.5.5 today.
