### ISSUE TITLE
Server link in the documentation

### ISSUE THREAD

**Issue by roipoussiere** [YunoHost-Apps/freshrss_ynh#39]
> API (mini) How To :
> * Into your user profile : Settings > profil
> * Setup an API password
> * Check the API is working : https://exemple.tld/rss/i/api/greader.php
> * Setup your client with : username : ynh user, password : the password you just setup, url https://exemple.tld/rss/i/api/greader.php
> 

To connect my EasyRSS Android app to FreshRSS, I have entered:

    https://exemple.tld/rss/api/greader.php

Without the `i/`. Otherwise it didn't work.

**Comment by plopoyop** [comment]
Fixed, thanks
