### ISSUE TITLE
Problem after user creation

### ISSUE THREAD

**Issue by manuelleduc** [YunoHost-Apps/freshrss_ynh#41]
Hello,

This issue might be related to #26. 

I just created a new user in my ynh instance for a friend (until then, I was the only user).

When fressh rss is accessed from this new account, the front page looks fine, but when clicking on "Subscriptions Management", the following message is displayed:

```
### Application problem ###
Permission is denied for `/var/www/freshrss/data/users/ronane/log.txt`
```

I went back to freesh using my own ynh account and added a new user with the same login as the new ynh account and it's now working fine.

Conclusion: I guess something is broken on the user synchronisation between yunohost and freshrss_ynh

Cheers

PS: You are doing an awesome work at building the ynh ecosystem, I'm a big fan :)

**Comment by plopoyop** [comment]
Hi,
It should be fixed into https://github.com/YunoHost-Apps/freshrss_ynh/pull/43

Thank you, by reporting bugs, you also participate to ynh ecosystem.
