### ISSUE TITLE
Commit is not up to date in the community.json

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/freshrss_ynh#46]
Hellow,

I found that the commit on [community.json](https://github.com/YunoHost/apps/blob/master/community.json) is outdated, hence people installing the app via this list won't benefit from the last upgrades / improvements ...

Please create a PR to update it on the list (I do not maintain this app so it's not relevant for me to do it and it might be refused...)

ProTip™ : possibly you can now set the commit to 'HEAD', to use the latest commit of master automatically in the future. If you do this, it is strongly recommended to use a 'testing' branch for changes that are not deemed stable yet.

**Comment by plopoyop** [comment]
Just did it.
Thanks for the tip, it'll be easier that way ;)
