### ISSUE TITLE
Missing php packages moving to YnH 3.0

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/freshrss_ynh#49]
After a restore from YnH 2.7 on a 3.0.
Then I upgraded my FreshRSS instance.
Then my feeds were no more getting updated.

I discovered that there were missing php packages:

```bash
apt install php-curl php-zip
```

Now, it’s working perfectly!

**Comment by moutonjr** [comment]
+1 in my side, these deps are missing.

**Comment by plopoyop** [comment]
Should be fixed on https://github.com/YunoHost-Apps/freshrss_ynh/commit/40c2b9082ce0ba5962b75b953a0ef3d187ea7e93
