### ISSUE TITLE
Dépendances non statisfaites / suppression de freshrss-ynh-deps

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#50]
J'ai actuellement l'erreur suivante en voulant mettre à jour mes paquets, ou freshrss:

```
 Les paquets suivants contiennent des dépendances non satisfaites :

  freshrss-ynh-deps : Dépend: php-cli mais il n'est pas installable
                     Dépend: php-gmp mais il n'est pas installable
                     Dépend: php-curl mais il n'est pas installable
                     Dépend: php-zip mais il n'est pas installable
```

Je n'ai le choix que de supprimer le paquet `freshrss-ynh-deps`.

Dois-je le faire ?
Ces dépendances sont-elles spécifiques à Debian 9 ? (je suis toujours sur Debian 8)

**Comment by plopoyop** [comment]
Salut,
En effet, les packets php de debian de contiennent plus la version (anciennement php5-cli par exemple)

Je n'ai plus de debian Jessie pour faire des tests, j'ai gardé la branche https://github.com/YunoHost-Apps/freshrss_ynh/tree/jessie-ynh-2 pour concerver une version compatible debian jessie.

Lors de la dernière mis à jour du package, j'ai fait une grosse passe sur le code, je ne suis pas sur que les helpers et configuration que j'ai mis en place soit compatibles avec ynh 2.7.

**Comment by lapineige** [comment]
Je n'ai pas pu mettre à jour vers cette version (j'avais déjà utilisé la nouvelle).
J'ai supprimé le paquet `freshrss-ynh-deps`, puis lancé la mise à jour (vers la branche jessie), c'est bon :)
