### ISSUE TITLE
Error while adding a user - hook "post_user_create"

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/freshrss_ynh#53]
Hello,

While adding a user, there are errors shown in the Yunohost administration panel.

Could you have a look ?

## Issue

![yunohost_freshrss](https://user-images.githubusercontent.com/17145502/47159577-757d5e80-d2ee-11e8-835f-2ccba8fef028.png)

> Échec de l’exécution du script « /etc/yunohost/hooks.d/post_user_create/50-freshrss »
> chown: impossible d'accéder à '/var/www/APPNAMETOCHANGE/data/users/XXXXXX/': Aucun fichier ou dossier de ce type
> sudo: /var/www/APPNAMETOCHANGE/cli/create-user.php : commande introuvable
> L'utilisateur a été créé
> La configuration de SSOwat a été générée

Link to the script : https://github.com/YunoHost-Apps/freshrss_ynh/blob/master/hooks/post_user_create

## Yunohost version

![yunohost_freshrss_env](https://user-images.githubusercontent.com/17145502/47160343-056fd800-d2f0-11e8-917f-ba3d33e3a819.png)

**Comment by plopoyop** [comment]
Hi,
I made a mistake into https://github.com/YunoHost-Apps/freshrss_ynh/pull/43/commits/12b078d680da15ab34ea00a377773b98f426e7e3

I change app name in install script but not in update. So, after upgrading the app, the hooks are messed up.

I'll fix this this evening. I should be quick.

**Comment by plopoyop** [comment]
Hi,
It should be fixed into :
https://github.com/YunoHost-Apps/freshrss_ynh/commit/3a137d0bf4fcf320655c18d3ba90e5b604742661

thanks for notifying me.
