### ISSUE TITLE
/api should be in "skipped_urls" for easyrss android app to work

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/freshrss_ynh#57]
Hi
As the app now don't have public mode the domain.tld/api need to be in "skipped_urls" to work with android apps.

**Comment by anmol26s** [comment]
And even Fail2ban support for failed /api attempts would be great.

**Comment by plopoyop** [comment]
Hi,
Yep, the app have evolved, greader.php is not the only api anymore.
I need to change https://github.com/YunoHost-Apps/freshrss_ynh/blob/master/scripts/install#L108 
I'll do it as soon as I can.

**Comment by plopoyop** [comment]
Upgraded into : https://github.com/YunoHost-Apps/freshrss_ynh/pull/61
