### ISSUE TITLE
Yunohost installation failed

### ISSUE THREAD

**Issue by prysme01** [YunoHost-Apps/freshrss_ynh#65]
Please find the log file here
 https://paste.yunohost.org/raw/ameticajof

**Comment by plopoyop** [comment]
look like you are missing curl.
It is weird, can you install it manually, 
I'll add it to the requirements but not before I finish the full rework branch.

**Comment by prysme01** [comment]
I did have curl

root@ns322828:~# apt install php-curl
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
php-curl is already the newest version (1:7.0+49).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
root@ns322828:~# apt install curl
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
curl is already the newest version (7.52.1-5+deb9u9).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

**Comment by prysme01** [comment]
nevermind, now it is working .. maybe I was missing it at this time. but now it's working.

**Comment by plopoyop** [comment]
Did you install another package ?

I am opening another issue to keep in mind I should add curl as a dependency.
