### ISSUE TITLE
Favicons lost on upgrade

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/freshrss_ynh#73]
Hi,

each time I upgrade the app I lose all my favicons.

To fix it I need to manually `rm /var/www/freshrss/favicons/*.ico` and then re-fetch all my feeds. I don't know if there is a better way…

**Comment by plopoyop** [comment]
It is weird, I use to have this problem when I created to package but not since.
Before deleting the favicons, next time, can you check the permission ?

**Comment by nicofrand** [comment]
Sure, will do!
