### ISSUE TITLE
pm.max_children limit reached

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/freshrss_ynh#75]
Hi,

while trying to understand why my freshrss cron is not running anymore I took a look at `/var/log/php7.0-fpm.log` and noticed this warning:

```bash
WARNING: [pool freshrss] server reached pm.max_children setting (5), consider raising it
```

I thought I should open a ticket so that issue might be fixed in the nginx configuration?

**Comment by plopoyop** [comment]
Does it have something to do with :  https://github.com/YunoHost-Apps/freshrss_ynh/issues/76 ?

**Comment by nicofrand** [comment]
I honestly have no idea. I found it while trying to debug my cron issue indeed but I don't why both would be related?

Feel free to close if you feel like it. I just wanted to create the ticket in case that was of any importance.

**Comment by notarobot63** [comment]
Same here, and I have only 2 or 3 feeds that are updating instead of more than 100...
I remove the FreshRss.log file in /tmp but nothing has changed.

**Comment by notarobot63** [comment]
I raised `pm.max_children` in `/etc/php/7.0/fpm/pool.d/freshrss.conf` at 15 and restarted php-fpm.
After launching a new request it seems to have worked.
