### ISSUE TITLE
CRON cannot write in log file

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/freshrss_ynh#76]
Hi,

my `/tmp/FreshRSS.log` file is not updated at each cron call.

I tried manually:

```bash
root@nicofrand:/var/log/yunohost# su - freshrss -s /bin/bash -c "/usr/bin/php7.0 /var/www/freshrss/app/actualize_script.php > /tmp/FreshRSS.log"                                            
-su: /tmp/FreshRSS.log: Permission denied
```

It appears there is a permission issue on it. Below the access rights on the file:

```bash
root@nicofrand:/var/log/yunohost# ls -l /tmp/FreshRSS.log
-rw-r--r-- 1 www-data www-data 253 Aug  7 11:52 /tmp/FreshRSS.log
```

**Comment by nicofrand** [comment]
`chmod freshrss /tmp/FreshRSS.log` fixes it.

**Comment by plopoyop** [comment]
Hi, sorry for the delay
Yes, it's been fixed in https://github.com/YunoHost-Apps/freshrss_ynh/commit/db12c853b2fc37aed5c1339c88b674909c39c8e4 
sorry about that. I should merge the testing branch

**Comment by nicofrand** [comment]
Sorry I did not see that!
