### ISSUE TITLE
failed to restore

### ISSUE THREAD

**Issue by jerometerrier** [YunoHost-Apps/freshrss_ynh#78]
Bonjour à tous,

j'ai un problème de restauration freshrss.
L'application a été désinstallée puis réinstallée pour une mise à jour yunohost mais avec erreur.
En effet, la restauration ne fonctionne pas.
A chaque fois, l'erreur est :  "Cette application est déjà installée. L’URL ne peut pas être changé simplement par cette fonction. Regardez si cela est disponible avec `app changeurl`." Sauf que l'application n'est pas installée.

J’ai tenté la restauration via l’interface web, en ligne de commande. J’ai remis yunohost à jour une nouvelle fois, retenter la restauration, j’ai redémarrer la VM… Tenté la restauration sur une machine toute fraiche...Rien n’y fait.

Mon serveur YunoHost
Matériel: VM Debian9 sur NAS Qnap TS-251
Version de YunoHost: 3.6.4.6

Voici les logs :

Log erreur FreshRSS :
https://paste.yunohost.org/mefibivare.sql

Merci

**Comment by lapineige** [comment]
Je ferme le ticket vu qu'il est ancien, si le problème persiste n'hésite pas à réouvrir.
