### ISSUE TITLE
Add php-gpm as dependency

### ISSUE THREAD

**Issue by roukydesbois** [YunoHost-Apps/freshrss_ynh#81]
I've had to install php-gpm in order to make the Android app FreshRSS work, it would be nice to have it installed at install and upgrade to have the app working out of the box!

**Comment by Alkarex** [comment]
For reference, a list of PHP extensions can be found in
https://github.com/FreshRSS/FreshRSS/blob/dev/Docker/Dockerfile-Alpine

The following line is available by default in most distributions (e.g. Debian / Ubuntu)
`php7-curl php7-gmp php7-intl php7-mbstring php7-xml php7-zip`
while this next line is for distributions such as Alpine, in which most PHP extensions must be explicitly enabled:
`php7-ctype php7-dom php7-fileinfo php7-iconv php7-json php7-opcache php7-session php7-simplexml php7-xmlreader php7-zlib`

**Comment by Alkarex** [comment]
For the record, `php-gmp` is only required for legacy 32-bit platforms.

**Comment by roukydesbois** [comment]
Thanks @Alkarex for the explanation! I'm running Yunohost on an Armbian Stretch (4.19.57-sunxi #5.90 SMP Fri Jul 5 17:58:43 CEST 2019 armv7l GNU/Linux) - I haven't found the default php packages for this distrib.

**Comment by Alkarex** [comment]
https://github.com/YunoHost-Apps/freshrss_ynh/pull/83
