### ISSUE TITLE
Upgrade to 0.15 failed due to dependencies

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/freshrss_ynh#86]
Hi,

the upgrade to version 0.15 failed on my server. Here are the logs: https://paste.yunohost.org/raw/arimahupak

It seems `php-gmd` and `php-sqlite3` could not be installed.
I tried manually but there were issues:

```
root@nicofrand:/home/admin# apt install php-gmp                                                          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php-gmp : Depends: php7.0-gmp but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
```
root@nicofrand:/home/admin# apt install php7.0-gmp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-gmp : Depends: php7.0-common (= 7.0.33-0+deb9u6) but 7.0.33-12+0~20191026.23+debian9~1.gbp940de0is to be installed
E: Unable to correct problems, you have held broken packages
```

I don't know how to fix this php7.0-common issue though… Could you help?

Thanks in advance!

**Comment by Alkarex** [comment]
Maybe relevant https://askubuntu.com/questions/564282/apt-get-unmet-dependencies-but-it-is-not-going-to-be-installed
If it requires a new release, it could be done at the same time than the just-released https://github.com/FreshRSS/FreshRSS/releases/tag/1.15.3

**Comment by nicofrand** [comment]
I really don't feel like removing any package and I am not sure it would fix it.
I wonder why php7.0-gmp would require a specific version of php7.0-common and not above…

**Comment by Alkarex** [comment]
@nicofrand Can you run `apt update && apt dist-upgrade && apt autoremove` before trying again?

**Comment by nicofrand** [comment]
I am having issues with yunohost upgrade right now (technical issues with their server) but it only suggests to upgrade non related packets (docker, nodejs, yunohost-admin).

```
root@nicofrand:/home/admin# apt install php7.0-gmp                                                                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-gmp : Depends: php7.0-common (= 7.0.33-0+deb9u6) but 7.0.33-12+0~20191026.23+debian9~1.gbp940de0 is to be installed
E: Unable to correct problems, you have held broken packages.
```

```
root@nicofrand:/home/admin# apt-cache policy php7.0-common
php7.0-common:
  Installed: 7.0.33-12+0~20191026.23+debian9~1.gbp940de0
  Candidate: 7.0.33-12+0~20191026.23+debian9~1.gbp940de0
  Version table:
 *** 7.0.33-12+0~20191026.23+debian9~1.gbp940de0 100
        100 /var/lib/dpkg/status
     7.0.33-0+deb9u6 500
        500 http://security.debian.org stretch/updates/main amd64 Packages
     7.0.33-0+deb9u3 500
        500 http://debian.mirrors.ovh.net/debian stretch/main amd64 Packages
```

**Comment by plopoyop** [comment]
Some yunohost package install the sury repository to install php version not included into debian.
I think you have a problem with sury packages. You may ask yunohost forum.
If you want to update freshrss, you can disable sury repository and install update.

**Comment by nicofrand** [comment]
I don't think that will help since the version already is installed.
I'll try to find which package added the repo.

There is a MR for nextcloud with it already: https://github.com/YunoHost-Apps/nextcloud_ynh/pull/229/files

**Comment by nicofrand** [comment]
Might be related to an update before this fix: https://github.com/YunoHost/yunohost/commit/854e52c21e0d5a6e10d122f8954b34c182c4de44

Anyway, I close, thanks
