### ISSUE TITLE
FreshRSS 1.16.0

### ISSUE THREAD

**Issue by Alkarex** [YunoHost-Apps/freshrss_ynh#93]
Just a heads-up that FreshRSS 1.16.0 is in RC and should be released in the coming days
https://github.com/FreshRSS/FreshRSS/issues/2871
So you may want to skip 1.15.3 if that version was not fully released yet for Yunohost.
Feedback welcome, especially if anything can be made to make it easier for Yunohost.

**Comment by plopoyop** [comment]
Hi,
1.15.3 is released. The PR https://github.com/YunoHost-Apps/freshrss_ynh/pull/89 was not merge because nobody tested it.
I merged it this week.
This week end, I am going to test the install process on the 1.16.0 RC. So I'll be ready to release just after you.

**Comment by Alkarex** [comment]
Ok 👍🏻

**Comment by Fipaddict** [comment]
Hi,


> So you may want to skip 1.15.3 if that version was not fully released yet for Yunohost.
> Feedback welcome, especially if anything can be made to make it easier for Yunohost.

Hi, I would like to help if I can. I'm ready to make some tests and give some feedback but I would need some help to make them because I have some doubt about my skill ;-) (even in english ;) )
At this time, I have VPS with an up-to-date Yunohost (3.7.0.12) and FreshRSS (1.15.3~ynh1) on it. I can also make some test on VM if necessary.
As you want or need.

**Comment by plopoyop** [comment]
Usually, I test upgrade on my VM and on my personal server.
Still I don't have all the use case (for example, I did know hooks were not working).
That's why I usually wait to have some feedback before merging.
If you agree to test the testing branch also, I could merge faster without fear.

**Comment by Alkarex** [comment]
Could one of you make me a temporary test account?
I would like to check a few things such as the API and WebSub

**Comment by plopoyop** [comment]
@Alkarex in fact, I can't do any test until there is a release or pre-release to download.

**Comment by Fipaddict** [comment]
> Could one of you make me a temporary test account?
> I would like to check a few things such as the API and WebSub

I do it on my VPS. how can I send information to you ?

**Comment by Alkarex** [comment]
@plopoyop 
Here you are https://github.com/FreshRSS/FreshRSS/archive/c9b5e8b5271cc59598a4fbcea5ff93698aab2eea.zip
You can always pick any commit of the /master branch, and check the *Download ZIP* option

**Comment by Alkarex** [comment]
Just for the record, @Fipaddict found me on our Framateam. Otherwise, [email](https://alexandre.alapetite.fr/cv/) is also fine :-)

**Comment by Alkarex** [comment]
P.S.: Link updated above to include a `.tar.gz` version @plopoyop

**Comment by Alkarex** [comment]
@plopoyop A few quick tests - I can open some new issues for those you find relevant. I am using a test account from @Fipaddict (thanks :-))

## Login issue
I was able to login once, and now I cannot anymore, even from a fresh blank browser
![image](https://user-images.githubusercontent.com/1008324/78437867-535cd500-7677-11ea-908e-8b69a2429508.png)

## UI overlay issue
I cannot close the feed details (by clicking anywhere on the left part) (maybe due to the YunoHost overlay logo?)
![image](https://user-images.githubusercontent.com/1008324/78438535-843d0a00-7677-11ea-9955-9404e04f070f.png)

Waiting for a working demo account to test some more :-)

**Comment by lapineige** [comment]
For the second issue: I did not have this problem, but I don't have Yunohost icon (maybe I removed it, I don't remember)

**Comment by Alkarex** [comment]
@lapineige Does the API test work on your instance?

**Comment by Alkarex** [comment]
@lapineige Could you also please test WebSub? I can explain more if needed

**Comment by lapineige** [comment]
What is this API test ? (#69 ? <- No)

What is WebSub ?

**Comment by Alkarex** [comment]
WebSub is to receive articles instantly by push, instead of having to wait for the next refresh (pull).
For instance, we a new post is made in https://push-pub.appspot.com/ I receive it instantly in my FreshRSS instance. I suspect a write access problem in `data\PubSubHubbub\*\`

**Comment by Alkarex** [comment]
If that could help, we could have a little teleconference @plopoyop to sort out those few issues

**Comment by plopoyop** [comment]
I am on framateam right now if you are available

**Comment by Fipaddict** [comment]
@plopoyop : If you can say me how to do it, I'm ready to install RC 1.16.0 on my YNH. Currently, I only do upgrades via the YNH admin.

**Comment by plopoyop** [comment]
1.16.0 update has no problem, so I did not push the branch, waiting for the final.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/releases/tag/1.16.0 🚀

**Comment by plopoyop** [comment]
In testing branch : https://github.com/YunoHost-Apps/freshrss_ynh/commit/1528f65f63c5139482f5c14b621c79e478807ece
