### ISSUE TITLE
Mysql service fails because of invalid tablespace flags

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#94]
My mysql server crashed and can't restart, with this error message:
`InnoDB: Error: invalid tablespace flags in tablespace ./freshrss/mypseudo_entrytmp.ibd (table freshrss/mypseudo_entrytmp)`

As a result, all apps relying on Mysql are crashed, as well as the upgrade :(

Do you know how I could repair that ?

**Comment by plopoyop** [comment]
Hi,
That is not a freshrss error. More a innodb/mariadb problem.

You can have a look at the reply in : https://dba.stackexchange.com/questions/202345/wont-start-innodb-corrupted-page-tablespace-was-not-found
this guide looks well done too : 
https://forums.cpanel.net/resources/innodb-corruption-repair-guide.395/

I don't know the utility of the table `_entrytmp`
Since the name is tmp, if the content is not important (you should ask on freshrss project). You could remove the table and recreate it after mariadb has restarted.

**Comment by Alkarex** [comment]
Yes, that table can be dropped and re-created if needed. It is only used to temporarily store articles during a refresh, to sort them before final insertion in the main table.

**Comment by plopoyop** [comment]
There are some article on google that help to restart mysql by removing the corrupted table.

**Comment by Alkarex** [comment]
BTW, FreshRSS should attempt to recreate that table when it observes an error.
If not, here is the manual template https://github.com/FreshRSS/FreshRSS/blob/bd036425aa495824b13a17891698a14d52ec93ba/app/SQL/install.sql.sqlite.php#L67-L85

**Comment by lapineige** [comment]
Ok, I'll see if I can connect to the database, and drop (?) that table without destroying everything 😅

**Comment by lapineige** [comment]
I can't figure out how to use mysql…
I tried to import Yunohost helper, and do a dump (as a backup), with:
>  ynh_mysql_dump_db --database="freshrss" > db.sql

But: `Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory") when trying to connect`

**Comment by plopoyop** [comment]
:warning: Big F*cking Warning !!! I am not responsible if you get errors / damage.

Make backup of the directory : `/var/lib/mysql/freshrss`
Remove the file :  `/var/lib/mysql/freshrss/mypseudo_entrytmp.ibd`
Start mariadb
Recreate the table `mypseudo_entrytmp.ibd`
This is the solution you can find on google, I have done it only once in my career. Mysql is flexible and is able to start with a missing file but it still can be harmful (if you are unlucky).

**Comment by lapineige** [comment]
The result when I start mysql service:
`InnoDB: Error: Space id and page n:o stored in the page read in are 2182:14168, should be 0:469!"`

**Comment by plopoyop** [comment]
hum, I don't know on this one.
Maybe, try to remove this file too.

**Comment by Alkarex** [comment]
This looks like a filesystem issue. Do you have enough space on your hard-disk? What kind of hard-disk / server is it?

**Comment by lapineige** [comment]
I removed the other file. No error message shown, but it doesn't start. While digging a bit deeper in the log, I have found only this :
> [ERROR] mysqld got signal 6

**Comment by Alkarex** [comment]
> It's an SD card, on a raspberry pi.

That is the most likely culprit, @lapineige . SD cards have a quite high likelihood of random IO error, and there are significant quality differences between SD card models. Although I have never experienced any problem at home with my SD card, I have used dozens of Raspberry Pis at work, and regularly observed such problems. Sometimes, reformatting can help for a while, but those IO errors often damage the SD card permanently.

So a few months ago, I have plugged an old SSD harddisk to my Raspberry Pi via USB3 (through a cheap SATA to USB3 adapter), to proactively avoid such issues, and I can recommand this approach.

**Comment by lapineige** [comment]
I knew about this, yet the way it happens is strange ^^
I thought my SD card would just die one day.

The weird thing is that everything seems to work fine, except mysql that failed.
Hopefully I have a weekly backup, and the last one was made… on Sunday, early in the morning… and the issue appeared after that.
I hope all databases were dumped correctly…

**Comment by Alkarex** [comment]
Most of the cases I observed are SD cards, which suddenly are not writeable, and then not readable. But I also experienced several cases with random bit/byte changes, with some *interesting* consequences...

**Comment by Alkarex** [comment]
By the way, for backups or migrations, remember FreshRSS's SQLite export/import feature (from/to any database) https://github.com/FreshRSS/FreshRSS/blob/master/cli/README.md

**Comment by lapineige** [comment]
Well, it seems that the backup fails partway… some apps were backup, not all :(. Maybe the issue happened at that point.
I'll save what I can, then maybe duplicate the whole SD card content to another one 🤔

@plopoyop in the case of this app, you use the helper to do a simple dump of the database, right ?

**Comment by lapineige** [comment]
(For the record, in case someone else face this issue, I opened a topic in the forum: https://forum.yunohost.org/t/comment-faire-une-sauvegarde-de-freshrss-wallabag-nextcloud-sans-acces-a-la-base-de-donnees/10828

**Comment by lapineige** [comment]
One last question and I stop spamming this issue (it's a bit off-topic now): @plopoyop do you know if I can safely delete FreshRSS without touching the rest of mysql (Nextcloud, …), and then restore a backup ?
If that the case, how ? By removing `/var/lib/mysql/freshrss` ?

**Comment by lapineige** [comment]
For you information, I was able to repair mysql database and remove FreshRSS + restore a backup. It was not related to FreshRSS nor Yunohost.
Details here: https://forum.yunohost.org/t/comment-faire-une-sauvegarde-de-freshrss-wallabag-nextcloud-sans-acces-a-la-base-de-donnees/10828/14

Thanks again for your help :)
