### ISSUE TITLE
During installation, add "FreshRSS" permission for the "visitors" group to accept connection from a smartphone application like FreshRSSAndroid

### ISSUE THREAD

**Issue by Fipaddict** [YunoHost-Apps/freshrss_ynh#95]
Since the YNH has modified the authorization mechanism, the group of "visitors" should be defined in such a way that freshrss can be used with external reader application such as FreshrssAndroid

cf https://yunohost.org/#/groups_and_permissions

**Comment by lapineige** [comment]
#69

**Comment by plopoyop** [comment]
I won't do that.
It break login system as described in https://github.com/YunoHost-Apps/freshrss_ynh/issues/93#issuecomment-609014393

I am looking at the new permission system.
I worked with Alkarex to check which directories should be open/closed.
I'll work on that this week-end.
For the record, I am using EasyRSS app on my phone + Ynh for at least 5 years. 
The API do work on ynh....
